name: Check Liquibase Schema

on:
  pull_request:

env:
  LIQUIBASE_VERSION: 4.27.0
  POSTGRES_VERSION: 15

  POSTGRES_USER: liquibase
  POSTGRES_PASSWORD: liquibase
  POSTGRES_DB: liquibase

  LIQUIBASE_CHANGELOG_PATH: ./changelog/db.changelog.xml

jobs:
  liquibase-update:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:${{ env.POSTGRES_VERSION }}
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U liquibase"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Liquibase
        run: |
          curl -sL "https://github.com/liquibase/liquibase/releases/download/v${LIQUIBASE_VERSION}/liquibase-${LIQUIBASE_VERSION}.tar.gz" | tar xz
          sudo mv liquibase /usr/local/bin/liquibase

      - name: Validate Liquibase changelog
        run: |
           liquibase \
           --changeLogFile=${LIQUIBASE_CHANGELOG_PATH} \
           validate

      - name: Run Liquibase update
        run: |
          liquibase \
            --changeLogFile=${LIQUIBASE_CHANGELOG_PATH} \
            --url=jdbc:postgresql://localhost:5432/${POSTGRES_DB} \
            --username=${POSTGRES_USER} \
            --password=${POSTGRES_PASSWORD} \
            update
