name: Publish DB Schema

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Changeset version'
        required: false
        default: ''
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    name: CDP-build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and Publish
        uses: DEFRA/cdp-build-action/publish-db-migrations@main
        with:
          path: ./changelog
          force: "true"
          version: ${{ inputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

